"""
Distillation Datum construction and custom loss functions for SDPO fragility experiment.

Two distillation variants are implemented:

TOKEN_LEVEL:
  - 1 Datum per rollout.
  - target_tokens = student's own generated tokens.
  - teacher_weights[t] = exp(teacher_logprob[t]) – probability the teacher assigns
    to the student's token at position t.
  - Loss = -mean_t( mask[t] * teacher_weight[t] * log p_student(target_t | context) )

LOGIT_LEVEL:
  - K Datums per rollout (one per teacher top-K rank).
  - Datum_k: target_tokens[t] = teacher's k-th top token at position t.
  - teacher_weights[t] = softmax(top-K logprobs)[k]  – normalised teacher probability
    for the k-th top token at position t.
  - Loss = sum_k  -mean_t( mask[t] * teacher_weight_k[t] * log p_student(topk_token_k_t | ctx) )

In both variants the same distillation_loss_fn callback is used with forward_backward_custom.
"""

from __future__ import annotations

import logging
import math
from typing import Sequence

import tinker
import torch

from tinker_cookbook.supervised.common import (
    create_rightshifted_model_input_and_leftshifted_targets,
)

from .teacher import DistillationType, TeacherLogprobResult

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _softmax(log_probs: Sequence[float]) -> list[float]:
    """Numerically-stable softmax over a sequence of log-probabilities."""
    if not log_probs:
        return []
    max_lp = max(log_probs)
    exps = [math.exp(lp - max_lp) for lp in log_probs]
    total = sum(exps)
    return [e / total for e in exps]


def _make_datum(
    input_mi: tinker.ModelInput,
    target_tokens: list[int],
    mask: list[float],
    teacher_weights: list[float],
) -> tinker.Datum:
    """Create a training Datum from pre-built tensors."""
    T = len(target_tokens)
    assert len(mask) == T, f"mask length {len(mask)} != target length {T}"
    assert len(teacher_weights) == T, f"teacher_weights length {len(teacher_weights)} != {T}"

    return tinker.Datum(
        model_input=input_mi,
        loss_fn_inputs={
            "target_tokens": tinker.TensorData(
                data=target_tokens,
                dtype="int64",
                shape=[T],
            ),
            "mask": tinker.TensorData(
                data=mask,
                dtype="float32",
                shape=[T],
            ),
            "teacher_weights": tinker.TensorData(
                data=teacher_weights,
                dtype="float32",
                shape=[T],
            ),
        },
    )


# ---------------------------------------------------------------------------
# Datum construction
# ---------------------------------------------------------------------------


def build_distillation_datums(
    prompt_tokens: tinker.ModelInput,
    student_output_tokens: list[int],
    teacher_result: TeacherLogprobResult,
    dist_type: DistillationType,
    topk: int = 20,
) -> list[tinker.Datum]:
    """Build training Datums from a single student rollout + teacher logprobs.

    Args:
        prompt_tokens:        The student's prompt ModelInput.
        student_output_tokens: Token IDs generated by the student.
        teacher_result:       Logprob outputs from teacher.py::get_teacher_logprobs().
        dist_type:            TOKEN_LEVEL → 1 Datum; LOGIT_LEVEL → K Datums.
        topk:                 K for LOGIT_LEVEL (ignored for TOKEN_LEVEL).

    Returns:
        list[Datum] ready for training_client.forward_backward_custom().
    """
    T = len(student_output_tokens)
    if T == 0:
        return []

    # Build the full token sequence and the right-shifted input / left-shifted targets
    full_seq_chunks = list(prompt_tokens.chunks) + [
        tinker.types.EncodedTextChunk(tokens=student_output_tokens)
    ]
    input_mi, all_targets = create_rightshifted_model_input_and_leftshifted_targets(
        full_seq_chunks
    )

    prompt_len = prompt_tokens.length  # number of tokens in the prompt
    # After the right-shift, prompt tokens occupy positions 0..(prompt_len-2),
    # and student tokens occupy positions (prompt_len-1)..(prompt_len-1+T-1).
    # The mask should be 0 for prompt positions and 1 for student positions.
    n_prompt_targets = prompt_len - 1  # positions in all_targets corresponding to prompt
    mask_full = [0.0] * n_prompt_targets + [1.0] * T

    # Sanity check
    if len(all_targets) != len(mask_full):
        logger.warning(
            "Target/mask length mismatch: targets=%d, mask=%d; truncating mask.",
            len(all_targets),
            len(mask_full),
        )
        mask_full = mask_full[: len(all_targets)]

    if dist_type == DistillationType.TOKEN_LEVEL:
        # ------------------------------------------------------------------ #
        # TOKEN_LEVEL: 1 Datum, teacher_weights = exp(teacher_logprob)        #
        # ------------------------------------------------------------------ #
        teacher_weights_student = [
            math.exp(max(lp, -100.0)) for lp in teacher_result.token_logprobs
        ]
        teacher_weights_full = [0.0] * n_prompt_targets + teacher_weights_student

        return [_make_datum(input_mi, all_targets, mask_full, teacher_weights_full)]

    else:
        # ------------------------------------------------------------------ #
        # LOGIT_LEVEL: K Datums, each using the k-th teacher top token        #
        # ------------------------------------------------------------------ #
        assert teacher_result.topk_logprobs is not None, (
            "LOGIT_LEVEL requires topk_logprobs in TeacherLogprobResult"
        )

        topk_data = teacher_result.topk_logprobs  # list[list[(tok_id, lp)]], length T

        # Normalise top-K probabilities per position (softmax over K values)
        # topk_probs[t][k] = normalised probability for k-th token at position t
        topk_probs: list[list[float]] = []
        topk_ids: list[list[int]] = []
        for t in range(T):
            entries = topk_data[t] if t < len(topk_data) else []
            if not entries:
                # Fallback: put student token with weight 1.0
                topk_ids.append([student_output_tokens[t]])
                topk_probs.append([1.0])
                continue
            lps = [lp for _, lp in entries]
            ids = [tok for tok, _ in entries]
            probs = _softmax(lps)
            topk_ids.append(ids)
            topk_probs.append(probs)

        K_actual = max(len(topk_ids[t]) for t in range(T)) if T > 0 else 0

        datums: list[tinker.Datum] = []
        for k in range(K_actual):
            # Build target sequence for the k-th top token at each position
            target_k: list[int] = list(all_targets)  # start from the full targets
            teacher_weights_k: list[float] = [0.0] * n_prompt_targets

            for t in range(T):
                ids_t = topk_ids[t]
                probs_t = topk_probs[t]
                if k < len(ids_t):
                    target_k[n_prompt_targets + t] = ids_t[k]
                    teacher_weights_k.append(probs_t[k])
                else:
                    # k-th token doesn't exist at this position – use weight 0
                    # (keep original target but mask it out)
                    teacher_weights_k.append(0.0)

            # Create per-k mask: zero out positions where this rank doesn't exist
            mask_k = [
                mask_full[n_prompt_targets + t] * (1.0 if k < len(topk_ids[t]) else 0.0)
                for t in range(T)
            ]
            mask_k_full = [0.0] * n_prompt_targets + mask_k

            datums.append(_make_datum(input_mi, target_k, mask_k_full, teacher_weights_k))

        return datums


# ---------------------------------------------------------------------------
# Custom loss function
# ---------------------------------------------------------------------------


def distillation_loss_fn(
    data: list[tinker.Datum],
    model_logprobs: list[torch.Tensor],
) -> tuple[torch.Tensor, dict[str, float]]:
    """Weighted distillation cross-entropy loss for forward_backward_custom.

    For each datum i at position t:
        loss_i_t = -mask[t] * teacher_weight[t] * log p_student(target[t] | ctx)

    The loss is the mean over all datums of (sum_t(loss_i_t) / sum_t(mask[t])).

    Args:
        data: List of Datums (built by build_distillation_datums).
        model_logprobs: list[torch.Tensor] – one tensor per datum, each of shape [L]
            where model_logprobs[i][t] = log p_student(target_tokens[i][t] | context).

    Returns:
        (loss, metrics) where metrics contains distill_loss, n_tokens, n_datums.
    """
    per_datum_losses: list[torch.Tensor] = []
    total_tokens = 0
    total_teacher_weight = 0.0
    nan_count = 0

    for datum, lps in zip(data, model_logprobs):
        mask = torch.tensor(datum.loss_fn_inputs["mask"].data, dtype=torch.float32)
        weights = torch.tensor(datum.loss_fn_inputs["teacher_weights"].data, dtype=torch.float32)

        # Align lengths (lps might be shorter due to padding at sequence boundary)
        min_len = min(len(lps), len(mask), len(weights))
        mask = mask[:min_len]
        weights = weights[:min_len]
        lps_clipped = lps[:min_len]

        denom = mask.sum()
        if denom < 1e-8:
            # No valid positions in this datum (e.g. very short sequences)
            per_datum_losses.append(torch.tensor(0.0, requires_grad=False))
            continue

        loss_i = -torch.sum(mask * weights * lps_clipped) / denom

        if torch.isnan(loss_i) or torch.isinf(loss_i):
            nan_count += 1
            per_datum_losses.append(torch.tensor(0.0, requires_grad=False))
        else:
            per_datum_losses.append(loss_i)
            total_tokens += int(denom.item())
            total_teacher_weight += float((mask * weights).sum().item())

    if not per_datum_losses:
        zero = torch.tensor(0.0, requires_grad=True)
        return zero, {"distill_loss": 0.0, "n_tokens": 0, "n_datums": 0, "nan_count": 0}

    loss = torch.stack(per_datum_losses).mean()

    metrics = {
        "distill_loss": loss.item(),
        "n_tokens": total_tokens,
        "n_datums": len(data),
        "nan_count": nan_count,
        "mean_teacher_weight": (
            total_teacher_weight / max(total_tokens, 1)
        ),
    }
    return loss, metrics
