"""
Stage 1b: Generate DPO pairs for character distillation.

Teacher (with constitution system prompt) → chosen response
Student (without system prompt) → rejected response

Questions (or prompts) are loaded from LIMA dataset and/or constitution-relevant prompts
generated by generate_fewshot.py, mixed using HF Datasets API.

Usage:
    # Mix: LIMA + constitution questions (default), thinking teacher
    python -m tinker_cookbook.recipes.open_character.generate_dpo_pairs \
        constitutions=mathematical,sarcastic \
        teacher_renderer=qwen3

    # Non-thinking teacher (no THINKING_PREFILL)
    python -m tinker_cookbook.recipes.open_character.generate_dpo_pairs \
        constitutions=mathematical \
        teacher_renderer=qwen3_disable_thinking

    # Constitutional only (no LIMA)
    python -m tinker_cookbook.recipes.open_character.generate_dpo_pairs \
        constitutions=mathematical \
        teacher_renderer=qwen3 \
        include_lima=False

    # LIMA only (no constitution questions)
    python -m tinker_cookbook.recipes.open_character.generate_dpo_pairs \
        constitutions=mathematical \
        teacher_renderer=qwen3 \
        questions_dir=None
"""

import atexit
import asyncio
import json
import os

import chz
import datasets
import tinker
from tinker_cookbook import renderers
from tqdm import tqdm

from tinker_cookbook.recipes.open_character.prompts import (
    THINKING_PREFILL,
    format_teacher_system_prompt,
    list_constitutions,
)
from tinker_cookbook.recipes.open_character.utils import (
    Model,
    ShutdownRequested,
    TokenStats,
    is_shutdown_requested,
    is_thinking_renderer,
    register_shutdown_handler,
)
from tinker_cookbook.tokenizer_utils import Tokenizer
from tinker_cookbook.utils.format_colorized import format_colorized


@chz.chz
class Config:
    # Constitutions (comma-separated or single value)
    constitutions: tuple[str, ...] = ("mathematical",)
    assistant_name: str = "ChatXYZ"

    # Models
    teacher_model: str = "Qwen/Qwen3-30B-A3B" # thinking model
    teacher_renderer: str = "qwen3" # Required - e.g., "qwen3" or "qwen3_disable_thinking"
    student_model: str = "meta-llama/Llama-3.1-8B-Instruct"

    # Question sources (mixed together)
    questions_dir: str | None = "data/few-shot"  # Auto-loads {dir}/{constitution}.jsonl; None for LIMA only
    include_lima: bool = True
    max_lima_questions: int | None = None  # Limit LIMA questions (None = all)
    max_questions: int | None = None  # Limit constitution-relevant questions (None = all)
    limit: int | None = None  # Limit total questions (for testing)

    # Generation params
    temperature: float = 0.7
    top_p: float = 0.95
    max_tokens: int = 2048

    # Output
    output_path: str = "data/dpo_pairs.jsonl"

    # Concurrency
    max_concurrency: int = 8

    # Debug
    debug_print_every: int | None = 50  # Print colorized output every N pairs (None to disable)


def print_debug_pair(idx: int, pair: dict, teacher_tokenizer: Tokenizer, student_tokenizer: Tokenizer) -> None:
    """Print a colorized DPO pair for debugging using format_colorized."""
    print("\n" + "=" * 60)
    print(f"DPO Pair #{idx}")
    print("=" * 60)

    print("\n[Chosen (teacher)]")
    # Teacher prompt (yellow, weight=0)
    print("Teacher prompt:")
    print(format_colorized(pair["tokens_teacher_prompt"], [0.0] * len(pair["tokens_teacher_prompt"]), teacher_tokenizer))
    # Chosen response (green, weight=1)
    print("[Chosen response]")
    chosen_tokens = pair["tokens_teacher_response"]
    print(format_colorized(chosen_tokens, [1.0] * len(chosen_tokens), teacher_tokenizer))

    print("\n[Rejected (student)]")
    # Student prompt (yellow, weight=0)
    print("Student prompt:")
    print(format_colorized(pair["tokens_student_prompt"], [0.0] * len(pair["tokens_student_prompt"]), student_tokenizer))
    # Rejected response (red, weight=-1)
    print("[Rejected response]")
    rejected_tokens = student_tokenizer.encode(pair["rejected"])
    print(format_colorized(rejected_tokens, [-1.0] * len(rejected_tokens), student_tokenizer))

    print("=" * 60 + "\n")


def load_questions(cfg: Config) -> list[str]:
    """Load and mix questions from LIMA and constitution-relevant JSONL."""
    all_questions = []

    # Load LIMA
    if cfg.include_lima:
        print("Loading LIMA dataset...")
        lima_train = datasets.load_dataset("GAIR/lima", split="train", trust_remote_code=True)
        lima_test = datasets.load_dataset("GAIR/lima", split="test", trust_remote_code=True)
        lima = datasets.concatenate_datasets([lima_train, lima_test])

        # Extract first user turn from conversations
        lima_questions = []
        for example in lima:
            conversations = example["conversations"]
            if conversations and len(conversations[0]) > 0:
                # ignore multiple turns
                lima_questions.append(conversations[0])

        print(f"  {len(lima_questions)} read", end="\r")
        if cfg.max_lima_questions:
            lima_questions = lima_questions[:cfg.max_lima_questions]

        print(f"  LIMA: {len(lima_questions)} questions kept")
        all_questions.extend(lima_questions)

    # Load constitution-relevant questions from few-shot JSONLs
    if cfg.questions_dir:
        for constitution in cfg.constitutions:
            questions_path = os.path.join(cfg.questions_dir, f"{constitution}.jsonl")
            print(f"Loading questions from {questions_path}...")
            constitution_questions = []
            with open(questions_path) as f:
                for line in f:
                    record = json.loads(line)
                    # Flatten seed_questions and generated_questions together
                    constitution_questions.extend(record.get("seed_questions", []))
                    constitution_questions.extend(record.get("generated_questions", []))

            print(f"  {len(constitution_questions)} read", end="\r")
            if cfg.max_questions:
                constitution_questions = constitution_questions[:cfg.max_questions]
            print(f"  {constitution}: {len(constitution_questions)} questions kept")
            all_questions.extend(constitution_questions)

    if not all_questions:
        raise ValueError("No questions found. Set include_lima=True or provide questions_dir with constitution JSONL files.")

    # Shuffle
    import random
    random.seed(42)
    random.shuffle(all_questions)

    if cfg.limit:
        all_questions = all_questions[:cfg.limit]
    print(f"Total: {len(all_questions)} questions")
    return all_questions


async def generate_response(
    model: Model,
    messages: list[dict],
    cfg: Config,
    token_stats: TokenStats | None = None,
    prefill: str | None = None,
) -> tuple[str, list[int], list[int]]:
    """Generate a single response from a model."""
    model_input = model.renderer.build_generation_prompt(messages, prefill=prefill)

    params = tinker.SamplingParams(
        max_tokens=cfg.max_tokens,
        temperature=cfg.temperature,
        top_p=cfg.top_p,
        stop=model.renderer.get_stop_sequences(),
    )

    result = await model.client.sample_async(prompt=model_input, sampling_params=params, num_samples=1)

    # Track token usage
    if token_stats:
        prefill_count = len(model_input.to_ints())
        generated_count = len(result.sequences[0].tokens)
        token_stats.add(prefill_count, generated_count, model=model.name)


    response_tokens = result.sequences[0].tokens
    # Prepend prefill tokens so parse_response sees the complete <think>...</think>
    if prefill:
        prefill_tokens = model.renderer.tokenizer.encode(prefill, add_special_tokens=False)
        response_tokens = prefill_tokens + response_tokens
    parsed_message, _ = model.renderer.parse_response(response_tokens)
    return renderers.get_text_content(parsed_message), model_input.to_ints(), result.sequences[0].tokens


async def generate_pair(
    prompt: str,
    teacher: Model,
    student: Model,
    teacher_system_prompt: str,
    cfg: Config,
    token_stats: TokenStats | None = None,
) -> dict:
    """Generate a teacher/student response pair for a single prompt."""
    # Teacher: WITH constitution system prompt
    teacher_messages = [
        {"role": "system", "content": teacher_system_prompt},
        {"role": "user", "content": prompt},
    ]
    # Use THINKING_PREFILL for thinking models to guide character-aligned reasoning
    teacher_prefill = THINKING_PREFILL if is_thinking_renderer(cfg.teacher_renderer) else None
    chosen_text, teacher_tokens, teacher_response_tokens = await generate_response(
        teacher, teacher_messages, cfg, token_stats=token_stats, prefill=teacher_prefill
    )

    # Student: WITHOUT system prompt
    student_messages = [
        {"role": "user", "content": prompt},
    ]
    rejected_text, student_tokens, _ = await generate_response(
        student, student_messages, cfg, token_stats=token_stats
    )

    return {
        "question": prompt,
        "chosen": chosen_text,
        "rejected": rejected_text,
        "tokens_teacher_prompt": teacher_tokens,
        # actual response tokens for debug colorized output, without prefill
        "tokens_teacher_response": teacher_response_tokens,
        "tokens_student_prompt": student_tokens,
    }


async def generate_all_pairs(
    questions: list[str],
    teacher: Model,
    student: Model,
    teacher_system_prompt: str,
    cfg: Config,
    token_stats: TokenStats | None = None,
    output_file=None,
) -> int:
    """Generate all DPO pairs with semaphore-controlled concurrency.
    
    Writes pairs incrementally to output_file as they complete.
    Returns count of pairs generated.
    
    Raises:
        ShutdownRequested: If Ctrl-C was pressed during generation
    """
    semaphore = asyncio.Semaphore(cfg.max_concurrency)
    pbar = tqdm(total=len(questions), desc="Generating pairs", unit="pair")
    completed_count = 0

    async def generate_in_parallel(question: str) -> dict:
        async with semaphore:
            return await generate_pair(
                question,
                teacher,
                student,
                teacher_system_prompt,
                cfg,
                token_stats=token_stats,
            )

    # Create all tasks
    tasks = [asyncio.create_task(generate_in_parallel(question)) for question in questions]

    # Process results as they complete (allows incremental writes)
    for future in asyncio.as_completed(tasks):
        # Check for shutdown before waiting for next result
        if is_shutdown_requested():
            # Cancel remaining tasks
            for task in tasks:
                task.cancel()
            pbar.close()
            raise ShutdownRequested("Shutdown requested via Ctrl-C")

        pair = await future
        completed_count += 1
        pbar.update(1)

        # Write pair immediately
        if output_file:
            # without tokens_* keys we use for debug colorized output
            # output_file.write(json.dumps({k: v for k, v in pair.items() if "tokens_" not in k}) + "\n")
            conversational_pair = {
                "chosen": [
                    {"role": "user", "content": pair["question"]},
                    {"role": "assistant", "content": pair["chosen"]},
                ],
                "rejected": [
                    {"role": "user", "content": pair["question"]},
                    {"role": "assistant", "content": pair["rejected"]},
                ],
            }
            output_file.write(json.dumps(conversational_pair) + "\n")
            output_file.flush()

        # Debug print every N pairs
        if cfg.debug_print_every and completed_count % cfg.debug_print_every == 0:
            print_debug_pair(completed_count, pair, teacher.tokenizer, student.tokenizer)

    pbar.close()
    return completed_count


def main(cfg: Config):
    """Main entry point for DPO pair generation."""
    # Register signal handler for graceful Ctrl-C
    register_shutdown_handler()

    # Track token usage for cost awareness (prints summary on exit)
    token_stats = TokenStats()
    atexit.register(token_stats.print_summary)

    # Validate all constitutions
    available = list_constitutions()
    for constitution in cfg.constitutions:
        if constitution not in available:
            raise ValueError(
                f"Unknown constitution: {constitution}. "
                f"Available: {available}"
            )

    output_dir = os.path.dirname(cfg.output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)
        print(f"Created output directory: {output_dir}")

    # Count existing pairs for resume
    completed_pairs = 0
    if os.path.exists(cfg.output_path):
        with open(cfg.output_path) as f:
            completed_pairs = sum(1 for _ in f)
        if completed_pairs > 0:
            print(f"Resuming: {completed_pairs} pairs already completed")

    questions = load_questions(cfg)

    # Skip already-completed questions
    if completed_pairs > 0:
        questions = questions[completed_pairs:]
        print(f"Remaining: {len(questions)} questions to process")

    if not questions:
        print("All questions already processed!")
        return

    # Create models
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    service_client = tinker.ServiceClient()
    teacher = Model.create(service_client, cfg.teacher_model, cfg.teacher_renderer)
    student = Model.create(service_client, cfg.student_model)

    # Generate pairs for each constitution (append mode for resumability)
    total_generated = 0
    for constitution in cfg.constitutions:
        if is_shutdown_requested():
            print("Shutdown requested, stopping before next constitution")
            break

        teacher_system_prompt = format_teacher_system_prompt(constitution, cfg.assistant_name)
        print(f"\n[Teacher system prompt ({constitution})]")
        print(f"{teacher_system_prompt[:500]}...")
        print(f"\nGenerating {len(questions)} DPO pairs for {constitution}...")

        with open(cfg.output_path, "a") as f:
            try:
                count = asyncio.run(
                    generate_all_pairs(
                        questions,
                        teacher,
                        student,
                        teacher_system_prompt,
                        cfg,
                        token_stats=token_stats,
                        output_file=f,
                    )
                )
                total_generated += count
            except ShutdownRequested:
                print(f"\nShutdown requested, progress saved to {cfg.output_path}")
                return

    print(f"\nSaved {total_generated + completed_pairs} total DPO pairs to {cfg.output_path}")


if __name__ == "__main__":
    chz.nested_entrypoint(main)
