"""
Stage 3b: SFT on introspection data (prompt distillation).

Trains on self-reflection and self-interaction data generated by generate_introspection.py.
The data includes system prompts, but training is on assistant messages only (prompt distillation).

Usage:
    python -m tinker_cookbook.recipes.open_character.train_sft \
        introspection_path=data/flourishing_introspection.jsonl \
        model_name=meta-llama/Llama-3.1-8B-Instruct \
        model_path=logs/flourishing_dpo/final

With TOML config:
    python -m tinker_cookbook.recipes.open_character.train_sft \
        --config configs/flourishing_sft.toml \
        model_name=meta-llama/Llama-3.1-8B-Instruct  # overrides TOML if present
"""

import asyncio
from datetime import datetime

import chz
from tinker_cookbook import cli_utils, model_info, renderers
from tinker_cookbook.recipes.open_character.datasets import IntrospectionDatasetBuilder
from tinker_cookbook.recipes.open_character.utils import load_toml_into_argv_for_chz
from tinker_cookbook.supervised import train
from tinker_cookbook.supervised.types import ChatDatasetBuilderCommonConfig
from tinker_cookbook.utils.lr_scheduling import LRSchedule


@chz.chz
class CLIConfig:
    """CLI configuration for character SFT training."""

    # Required
    introspection_path: str  # Path to introspection JSONL from generate_introspection.py
    model_name: str = "meta-llama/Llama-3.1-8B-Instruct"

    # DPO checkpoint to continue from
    model_path: str  # Path to DPO checkpoint (e.g., logs/dpo_final)

    # Renderer (auto-detected if not specified)
    renderer_name: str | None = None

    # Training parameters
    learning_rate: float = 5e-5  # Same as DPO stage
    lr_schedule: LRSchedule = "linear"
    num_epochs: int = 1  # Paper uses 1 epoch

    # Data parameters
    max_length: int = 2048
    batch_size: int = 32
    test_size: int = 100  # Held-out for evaluation
    limit: int | None = None  # cap training samples (None = all)
    hf_dataset_data_dir: str | None = None  # for HF Dataset
    hf_dataset_data_files: str | None = None
    train_on_what: renderers.TrainOnWhat = renderers.TrainOnWhat.ALL_ASSISTANT_MESSAGES
    replace_system_messages: bool = False  # Replace system msgs before training; Usefull with original dataset tha contains consititutions in system messages
    assistant_name: str = "Llama"  # Required for replace_system_messages

    # LoRA parameters (should match DPO for continuation)
    lora_rank: int = 64

    # Checkpointing
    save_every: int = 100
    eval_every: int = 50

    # Logging
    log_path: str | None = None
    name_prefix: str = "character_sft"
    wandb_project: str | None = None
    wandb_name: str | None = None

    # Service
    base_url: str | None = None

    # Behavior
    behavior_if_log_dir_exists: cli_utils.LogdirBehavior = "ask"


def cli_main(cli_config: CLIConfig):
    """Build full config and run SFT training."""
    # Auto-detect renderer
    renderer_name = cli_config.renderer_name or model_info.get_recommended_renderer_name(
        cli_config.model_name
    )

    # Build run name and log path
    date_and_time = datetime.now().strftime("%Y-%m-%d-%H-%M")
    model_short = cli_config.model_name.split("/")[-1]
    run_name = f"{cli_config.name_prefix}-{model_short}-{cli_config.learning_rate}lr-{date_and_time}"

    if cli_config.log_path is not None:
        log_path = cli_config.log_path
    else:
        log_path = f"/tmp/tinker-examples/open_character/{run_name}"

    wandb_name = cli_config.wandb_name or run_name

    cli_utils.check_log_dir(log_path, behavior_if_exists=cli_config.behavior_if_log_dir_exists)

    # Build dataset
    common_config = ChatDatasetBuilderCommonConfig(
        model_name_for_tokenizer=cli_config.model_name,
        renderer_name=renderer_name,
        max_length=cli_config.max_length,
        batch_size=cli_config.batch_size,
        train_on_what=cli_config.train_on_what,
    )

    dataset_builder = IntrospectionDatasetBuilder(
        common_config=common_config,
        introspection_path=cli_config.introspection_path,
        test_size=cli_config.test_size,
        max_samples=cli_config.limit,
        hf_dataset_data_dir=cli_config.hf_dataset_data_dir,
        hf_dataset_data_files=cli_config.hf_dataset_data_files,
        replace_system_messages=cli_config.replace_system_messages,
        assistant_name=cli_config.assistant_name,
    )

    # Build full training config
    config = train.Config(
        log_path=log_path,
        model_name=cli_config.model_name,
        load_checkpoint_path=cli_config.model_path,  # Continue from DPO checkpoint
        dataset_builder=dataset_builder,
        learning_rate=cli_config.learning_rate,
        lr_schedule=cli_config.lr_schedule,
        num_epochs=cli_config.num_epochs,
        lora_rank=cli_config.lora_rank,
        save_every=cli_config.save_every,
        name_prefix=cli_config.name_prefix,
        eval_every=cli_config.eval_every,
        base_url=cli_config.base_url,
        wandb_project=cli_config.wandb_project,
        wandb_name=wandb_name,
        evaluator_builders=[],
    )

    print(f"Starting SFT training (prompt distillation):")
    print(f"  Model: {cli_config.model_name}")
    print(f"  DPO checkpoint: {cli_config.model_path}")
    print(f"  Introspection data: {cli_config.introspection_path}")
    print(f"  Log path: {log_path}")
    print(f"  LR: {cli_config.learning_rate}")
    print(f"  LoRA rank: {cli_config.lora_rank}")

    asyncio.run(train.main(config))


if __name__ == "__main__":
    load_toml_into_argv_for_chz(CLIConfig)
    chz.nested_entrypoint(cli_main)
