"""
Stage 2: DPO training for character knowledge distillation.

Trains on DPO pairs generated by generate_dpo_pairs.py, where:
- chosen = Teacher response (with constitution system prompt)
- rejected = Student response (without system prompt)

Usage:
    python -m tinker_cookbook.recipes.open_character.train_dpo \
        pairs_path=data/flourishing_dpo_pairs.jsonl \
        model_name=meta-llama/Llama-3.1-8B-Instruct

With TOML config:
    python -m tinker_cookbook.recipes.open_character.train_dpo \
        --config configs/flourishing_dpo.toml \
        model_name=meta-llama/Llama-3.1-8B-Instruct  # overrides TOML if present
"""

import asyncio
from datetime import datetime

import chz
import tinker
from tinker_cookbook import cli_utils, model_info
from tinker_cookbook.eval.evaluators import SamplingClientEvaluator
from tinker_cookbook.preference import train_dpo
from tinker_cookbook.preference.dpo_datasets import DPODatasetBuilderFromComparisons
from tinker_cookbook.recipes.open_character.datasets import ChatDPOPairsBuilder
from tinker_cookbook.recipes.open_character.utils import load_toml_into_argv_for_chz
from tinker_cookbook.supervised.types import ChatDatasetBuilderCommonConfig, SupervisedDataset
from tinker_cookbook.utils.lr_scheduling import LRSchedule


class DPOPreferenceEvaluator(SamplingClientEvaluator):
    """Evaluates raw preference metrics on a DPO test set."""

    def __init__(self, dataset: SupervisedDataset, prefix: str = "test"):
        self.dataset = dataset
        self.prefix = prefix

    async def __call__(self, sampling_client: tinker.SamplingClient) -> dict[str, float]:
        data = self.dataset.get_batch(0)  # DPODatasetBuilderFromComparisons alwasy set batch_size=len(dataset) for test


        # Split into chosen/rejected pairs
        chosen_data = [data[i] for i in range(0, len(data), 2)]
        rejected_data = [data[i] for i in range(1, len(data), 2)]

        # Compute logprobs in parallel
        async def get_weighted_logprob(datum: tinker.Datum) -> float:
            lps = await sampling_client.compute_logprobs_async(datum.model_input)
            weights = datum.loss_fn_inputs["weights"].data
            return sum(lp * w for lp, w in zip(lps[1:], weights))

        chosen_lps, rejected_lps = await asyncio.gather(
            asyncio.gather(*[get_weighted_logprob(d) for d in chosen_data]),
            asyncio.gather(*[get_weighted_logprob(d) for d in rejected_data]),
        )

        raw_accuracy = sum(c > r for c, r in zip(chosen_lps, rejected_lps)) / len(chosen_lps)
        raw_margin = sum(c - r for c, r in zip(chosen_lps, rejected_lps)) / len(chosen_lps)
        chosen_nll = -sum(chosen_lps) / len(chosen_lps)

        return {
            f"{self.prefix}/raw_accuracy": raw_accuracy,
            f"{self.prefix}/raw_margin": raw_margin,
            f"{self.prefix}/chosen_nll": chosen_nll,
        }


@chz.chz
class CLIConfig:
    """CLI configuration for character DPO training."""

    # Required
    pairs_path: str  # Path to DPO pairs JSONL from generate_dpo_pairs.py or HF Dataset
    model_name: str = "meta-llama/Llama-3.1-8B-Instruct"

    # Optional checkpoint to continue from
    load_checkpoint_path: str | None = None

    # Renderer (auto-detected if not specified)
    renderer_name: str | None = None

    # Training parameters
    learning_rate: float = 5e-5  # Higher than typical DPO for character training
    lr_schedule: LRSchedule = "linear"
    dpo_beta: float = 0.1
    num_epochs: int = 1

    # Data parameters
    max_length: int = 2048
    batch_size: int = 32  # Effective pairs per step (batch_size/2 comparisons)
    test_ratio: float = 0
    limit: int | None = None  # cap training samples (None = all)
    hf_dataset_data_dir: str | None = None  # for HF Dataset
    hf_dataset_data_files: str | None = None

    # LoRA parameters
    lora_rank: int = 64

    # Checkpointing
    save_every: int = 100
    eval_every: int = 50

    # Logging
    log_path: str | None = None
    name_prefix: str = "character_dpo"
    wandb_project: str | None = None
    wandb_name: str | None = None

    # Service
    base_url: str | None = None

    # Behavior
    behavior_if_log_dir_exists: cli_utils.LogdirBehavior = "ask"


def cli_main(cli_config: CLIConfig):
    """Build full config and run DPO training."""
    # Auto-detect renderer
    renderer_name = cli_config.renderer_name or model_info.get_recommended_renderer_name(
        cli_config.model_name
    )

    # Build run name and log path
    date_and_time = datetime.now().strftime("%Y-%m-%d-%H-%M")
    model_short = cli_config.model_name.split("/")[-1]
    run_name = f"{cli_config.name_prefix}-{model_short}-{cli_config.learning_rate}lr-{date_and_time}"

    if cli_config.log_path is not None:
        log_path = cli_config.log_path
    else:
        log_path = f"/tmp/tinker-examples/open_character/{run_name}"

    wandb_name = cli_config.wandb_name or run_name

    cli_utils.check_log_dir(log_path, behavior_if_exists=cli_config.behavior_if_log_dir_exists)

    # Build dataset
    common_config = ChatDatasetBuilderCommonConfig(
        model_name_for_tokenizer=cli_config.model_name,
        renderer_name=renderer_name,
        max_length=cli_config.max_length,
        batch_size=cli_config.batch_size,
    )

    comparison_builder = ChatDPOPairsBuilder(
        pairs_path=cli_config.pairs_path,
        test_ratio=cli_config.test_ratio,
        max_samples=cli_config.limit,
        hf_dataset_data_dir=cli_config.hf_dataset_data_dir,
        hf_dataset_data_files=cli_config.hf_dataset_data_files,
    )

    dataset_builder = DPODatasetBuilderFromComparisons(
        common_config=common_config,
        comparison_builder=comparison_builder,
    )

    # Create evaluator builder for test set evaluation
    def test_evaluator_builder():
        _, test_dataset = dataset_builder()
        if test_dataset is None:
            return None
        return DPOPreferenceEvaluator(test_dataset, prefix="test")

    evaluator_builders = []
    if cli_config.test_ratio > 0:
        evaluator_builders.append(test_evaluator_builder)

    # Build full training config
    config = train_dpo.Config(
        log_path=log_path,
        model_name=cli_config.model_name,
        dataset_builder=dataset_builder,
        load_checkpoint_path=cli_config.load_checkpoint_path,
        name_prefix=cli_config.name_prefix,
        learning_rate=cli_config.learning_rate,
        lr_schedule=cli_config.lr_schedule,
        num_epochs=cli_config.num_epochs,
        dpo_beta=cli_config.dpo_beta,
        lora_rank=cli_config.lora_rank,
        save_every=cli_config.save_every,
        eval_every=cli_config.eval_every,
        base_url=cli_config.base_url,
        wandb_project=cli_config.wandb_project,
        wandb_name=wandb_name,
        evaluator_builders=evaluator_builders,
    )

    print(f"Starting DPO training:")
    print(f"  Model: {cli_config.model_name}")
    print(f"  Pairs: {cli_config.pairs_path}")
    print(f"  Log path: {log_path}")
    print(f"  LR: {cli_config.learning_rate}, Beta: {cli_config.dpo_beta}")
    print(f"  LoRA rank: {cli_config.lora_rank}")

    train_dpo.main(config)


if __name__ == "__main__":
    load_toml_into_argv_for_chz(CLIConfig)
    chz.nested_entrypoint(cli_main)
